### PR TITLE
add df_to_pandas

### PR DESCRIPTION
**Pull request by AndresAlgaba**
Issue #17 mentions the usefulness of a ```df_to_pandas``` method in the ```BasicProblem``` object. Based on the ```df_to_numpy``` code, I have added this method with some tests to check whether it results in identical arrays.

### CODE REVIEW

**Comment by AndresAlgaba** [comment]
I've also added a small example to the README.

**Comment by mrtzh** [comment]
Hi Andres, I appreciate the contribution. I just had a chance to look closer into it and I like what you propose.

There's one change I'd suggest. The attribute descriptions in `ACSIncome_categories` are from the the US Census documentation and are subject to change. I'd prefer not to hardwire these into the `folktables` codebase, since that would mean we'd have to react more strongly to future changes in the US Census documentation.

I think `ACSIncome_categories` is very faluable, but that it should live in the third party space. There are two options I see:

* Put it in the documentation as an example on how to use `df_to_pandas`
* Create a directory with `examples`

In either case, please add a note that these features are subject to change.

Does this sound good?

**Comment by AndresAlgaba** [comment]
Dear Moritz, thanks to you and the entire team for the fantastic effort on this library and the general contributions to the fairness literature!

I agree with your suggestion. I have placed such an example in the README. Could we merge this example with the content of the ```ACSIncome_categories.py``` in a Jupyter notebook and put it in an example folder referencing the US Census documentation? I would maybe leave the pandas and CSV-saving part in the README as this may be of interest to a general audience. 

Do you have any suggestions on grouping some variables, such as "OCCP," which contain too many categories?

As it is indeed a broader design choice, I will wait a few days before continuing to work on this such that the entire team has some time to consider the proposed changes.

**Comment by mrtzh** [comment]
It looks like folks had a chance to chime in and @millerjohnp is fine with your suggestion. So please update the pull request accordingly and I will go ahead and merge it. Thanks again for your contribution!

**Comment by AndresAlgaba** [comment]
Great! I have added the examples folder and refer to the ```categories``` and ```dummies``` arguments in the ```df_to_pandas``` method as "encoding categorical features". I have also slightly updated the README, most importantly the header by removing one # as I feel it may be a subsection on its own? Please let me know your thoughts about the changes and whether any updates are required.

**Pull request merged**
